package com.cccclab.expertsystemsimulator.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { ¡K }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Design extends AbsoluteLayout {
	public Design() {
		com.vaadin.ui.declarative.Design.read(this);
	}
}
